# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 939bd172822f7996f6458e45feb25850f97bda0c695bf8fbd0cc6698692fc08a1dbb2fa6fafa6de760b1c18663c058180eee2273b49ac97878c9ba8fd79d5344

test:
  secret_key_base: 97193c339d89a07d145c3323ee338c6cb4e9f776a3c48e15b203de447a3e3af3444854797a1d0dbf51f7251c0121aabe97b9226f8278287243b2c5a109138b34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
